### ISSUE TITLE
/response-headers broken with Flask 0.11

### ISSUE THREAD

**Issue by The-Compiler** [Runscope/httpbin#290]
Since updating from Flask 0.10.1 to 0.11.0, when trying to request `/response-headers` I get:

```
[...] ERROR in app: Exception on /response-headers [GET]
Traceback (most recent call last):
  File ".../site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File ".../site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".../site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File ".../site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../site-packages/httpbin/core.py", line 314, in response_headers
    response = jsonify(headers.lists())
  File ".../site-packages/httpbin/core.py", line 40, in jsonify
    response = flask_jsonify(*args, **kwargs)
  File ".../site-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File ".../site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File ".../json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File ".../json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File ".../json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File ".../site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File ".../json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <generator object MultiDict.lists at ...> is not JSON serializable
```

This is on Python 3.5 with httpbin 0.4.1.

I opened https://github.com/pallets/flask/issues/1825, but apparently this is a httpbin issue. It does `jsonify(headers.lists())`, and `headers.lists()` is a generator on Python 3 (despite [the Werkzeug docs not saying so](http://werkzeug.pocoo.org/docs/dev/datastructures/#werkzeug.datastructures.MultiDict.lists)).

I'm not sure why this worked with older Flask versions, but httpbin should apparently do `jsonify(list(headers.lists()))` here (and possibly in other places using a `MultiDict`).

**Comment by fxfitz** [comment]
+1, I'm seeing this issue as well (and has spread through to other popular projects as well)
